server:
  port: 9000
logging:
  level:
    org.springframework.security: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: remote
    password: remote
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "my-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/auth/callback"
              post-logout-redirect-uris:
                - "http://localhost:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
application:
  data:
    initialize: false